import assert from 'node:assert/strict';
import { it, mock } from 'node:test';
import Fastify from 'fastify';
import fp from 'fastify-plugin';
import { OpenAIImageGenerateRunnable } from '@talespin/ai';
import imageGeneration from '../../src/plugins/image-generation.js';
import { generationContext } from '../../src/services/generation-recovery.js';
import { MemoryStore } from '../memory-generation-store.js';

Object.assign(process.env, {
  AI_IMAGE_PROVIDER: 'openai',
  AI_IMAGE_EDIT_PROVIDER: 'openai',
  OPENAI_API_KEY: 'fixture-only',
});

it('retries failed uploads with the existing generated bytes', async () => {
  let providerCalls = 0;
  let uploadCalls = 0;
  const stub = mock.method(
    OpenAIImageGenerateRunnable.prototype,
    'invoke',
    async () => {
      providerCalls++;
      return {
        imageBuffer: Buffer.from([1]),
        contentType: 'image/png',
        providerMeta: {
          provider: 'openai',
          model: 'fixture',
          size: '1024x1024',
        },
      };
    },
  );
  const app = Fastify();
  await app.register(
    fp(
      async (fastify) => {
        fastify.decorate('cdn', {
          bucket: 'test',
          getPublicURL: () => 'https://cdn.test/map.png',
          findObjectByPrefix: async () => null,
          uploadBuffer: async () => {
            uploadCalls++;
            if (uploadCalls === 1) throw new Error('Temporary storage error');
            return { key: 'map.png', url: 'https://cdn.test/map.png' };
          },
        });
      },
      { name: 'cdn' },
    ),
  );
  await app.register(imageGeneration);
  try {
    const result = await generationContext.run(
      { scope: 'upload-retry', store: new MemoryStore() },
      () =>
        app.imageGen.generateImageToCdn({
          prompt: 'Map',
          purpose: 'map',
          keyPrefix: 'maps/',
        }),
    );
    assert.equal(result.url, 'https://cdn.test/map.png');
    assert.equal(uploadCalls, 2);
    assert.equal(providerCalls, 1);
  } finally {
    stub.mock.restore();
    await app.close();
  }
});

it('recovers an acknowledged-lost CDN artifact without another provider call', async () => {
  let providerCalls = 0;
  let artifact: { key: string; url: string } | null = null;
  const stub = mock.method(
    OpenAIImageGenerateRunnable.prototype,
    'invoke',
    async () => {
      providerCalls++;
      return {
        imageBuffer: Buffer.from([1]),
        contentType: 'image/png',
        providerMeta: {
          provider: 'openai',
          model: 'fixture',
          size: '1024x1024',
        },
      };
    },
  );
  const app = Fastify();
  await app.register(
    fp(
      async (fastify) => {
        fastify.decorate('cdn', {
          bucket: 'test',
          getPublicURL: () => 'https://cdn.test/map.png',
          findObjectByPrefix: async () => artifact,
          uploadBuffer: async () => {
            artifact = { key: 'map.png', url: 'https://cdn.test/map.png' };
            throw new Error('Upload response lost');
          },
        });
      },
      { name: 'cdn' },
    ),
  );
  await app.register(imageGeneration);
  const store = new MemoryStore();
  const run = () =>
    generationContext.run({ scope: 'lost-response', store }, () =>
      app.imageGen.generateImageToCdn({
        prompt: 'Map',
        purpose: 'map',
        keyPrefix: 'maps/',
      }),
    );
  try {
    await assert.rejects(run, /Upload response lost/);
    assert.equal((await run()).url, 'https://cdn.test/map.png');
    assert.equal(providerCalls, 1);
  } finally {
    stub.mock.restore();
    await app.close();
  }
});
